CREATE TABLE `customer` (
	`C_CUSTKEY` INT(11) NOT NULL,
	`C_MKTSEGMENT` CHAR(10) NULL DEFAULT NULL COLLATE 'latin1_bin',
	`C_NATIONKEY` INT(11) NULL DEFAULT NULL,
	`C_NAME` VARCHAR(25) NULL DEFAULT NULL COLLATE 'latin1_bin',
	`C_ADDRESS` VARCHAR(40) NULL DEFAULT NULL COLLATE 'latin1_bin',
	`C_PHONE` CHAR(15) NULL DEFAULT NULL COLLATE 'latin1_bin',
	`C_ACCTBAL` DECIMAL(10,2) NULL DEFAULT NULL,
	`C_COMMENT` VARCHAR(118) NULL DEFAULT NULL COLLATE 'latin1_bin',
	PRIMARY KEY (`C_CUSTKEY`),
	INDEX `CUSTOMER_FK1` (`C_NATIONKEY`)
)
COLLATE='latin1_swedish_ci'
ENGINE=TREESTORE;

CREATE TABLE `lineitem` (
	`L_SHIPDATE` DATE NULL DEFAULT NULL,
	`L_ORDERKEY` INT(11) NOT NULL,
	`L_DISCOUNT` DECIMAL(10,2) NOT NULL,
	`L_EXTENDEDPRICE` DECIMAL(10,2) NOT NULL,
	`L_SUPPKEY` INT(11) NOT NULL,
	`L_QUANTITY` INT(11) NOT NULL,
	`L_RETURNFLAG` CHAR(1) NULL DEFAULT NULL COLLATE 'latin1_bin',
	`L_PARTKEY` INT(11) NOT NULL,
	`L_LINESTATUS` CHAR(1) NULL DEFAULT NULL COLLATE 'latin1_bin',
	`L_TAX` DECIMAL(10,2) NOT NULL,
	`L_COMMITDATE` DATE NULL DEFAULT NULL,
	`L_RECEIPTDATE` DATE NULL DEFAULT NULL,
	`L_SHIPMODE` CHAR(10) NULL DEFAULT NULL COLLATE 'latin1_bin',
	`L_LINENUMBER` INT(11) NOT NULL,
	`L_SHIPINSTRUCT` CHAR(25) NULL DEFAULT NULL COLLATE 'latin1_bin',
	`L_COMMENT` VARCHAR(44) NULL DEFAULT NULL COLLATE 'latin1_bin',
	PRIMARY KEY (`L_ORDERKEY`, `L_LINENUMBER`),
	INDEX `LINEITEM_FK2` (`L_SUPPKEY`),
	INDEX `LINEITEM_FK3` (`L_PARTKEY`, `L_SUPPKEY`),
	INDEX `LI_SHP_DT_IDX` (`L_SHIPDATE`),
	INDEX `LI_COM_DT_IDX` (`L_COMMITDATE`),
	INDEX `LI_RCPT_DT_IDX` (`L_RECEIPTDATE`)
)
COLLATE='latin1_swedish_ci'
ENGINE=TREESTORE;

CREATE TABLE `nation` (
	`N_NATIONKEY` INT(11) NOT NULL,
	`N_NAME` CHAR(25) NULL DEFAULT NULL COLLATE 'latin1_bin',
	`N_REGIONKEY` INT(11) NULL DEFAULT NULL,
	`N_COMMENT` VARCHAR(152) NULL DEFAULT NULL COLLATE 'latin1_bin',
	PRIMARY KEY (`N_NATIONKEY`),
	INDEX `NATION_FK1` (`N_REGIONKEY`)
)
COLLATE='latin1_swedish_ci'
ENGINE=TREESTORE;
CREATE TABLE `orders` (
	`O_ORDERDATE` DATE NULL DEFAULT NULL,
	`O_ORDERKEY` INT(11) NOT NULL,
	`O_CUSTKEY` INT(11) NOT NULL,
	`O_ORDERPRIORITY` CHAR(15) NULL DEFAULT NULL COLLATE 'latin1_bin',
	`O_SHIPPRIORITY` INT(11) NULL DEFAULT NULL,
	`O_CLERK` CHAR(15) NULL DEFAULT NULL COLLATE 'latin1_bin',
	`O_ORDERSTATUS` CHAR(1) NULL DEFAULT NULL COLLATE 'latin1_bin',
	`O_TOTALPRICE` DECIMAL(10,2) NULL DEFAULT NULL,
	`O_COMMENT` VARCHAR(79) NULL DEFAULT NULL COLLATE 'latin1_bin',
	PRIMARY KEY (`O_ORDERKEY`),
	INDEX `ORDERS_FK1` (`O_CUSTKEY`),
	INDEX `ORDERS_DT_IDX` (`O_ORDERDATE`)
)
COLLATE='latin1_swedish_ci'
ENGINE=TREESTORE;
CREATE TABLE `part` (
	`P_PARTKEY` INT(11) NOT NULL,
	`P_TYPE` VARCHAR(25) NULL DEFAULT NULL COLLATE 'latin1_bin',
	`P_SIZE` INT(11) NULL DEFAULT NULL,
	`P_BRAND` CHAR(10) NULL DEFAULT NULL COLLATE 'latin1_bin',
	`P_NAME` VARCHAR(55) NULL DEFAULT NULL COLLATE 'latin1_bin',
	`P_CONTAINER` CHAR(10) NULL DEFAULT NULL COLLATE 'latin1_bin',
	`P_MFGR` CHAR(25) NULL DEFAULT NULL COLLATE 'latin1_bin',
	`P_RETAILPRICE` DECIMAL(10,2) NULL DEFAULT NULL,
	`P_COMMENT` VARCHAR(23) NULL DEFAULT NULL COLLATE 'latin1_bin',
	PRIMARY KEY (`P_PARTKEY`)
)
COLLATE='latin1_swedish_ci'
ENGINE=TREESTORE;
CREATE TABLE `partsupp` (
	`PS_PARTKEY` INT(11) NOT NULL,
	`PS_SUPPKEY` INT(11) NOT NULL,
	`PS_SUPPLYCOST` INT(11) NOT NULL,
	`PS_AVAILQTY` INT(11) NULL DEFAULT NULL,
	`PS_COMMENT` VARCHAR(199) NULL DEFAULT NULL COLLATE 'latin1_bin',
	PRIMARY KEY (`PS_PARTKEY`, `PS_SUPPKEY`),
	INDEX `PARTSUPP_FK2` (`PS_SUPPKEY`)
)
COLLATE='latin1_swedish_ci'
ENGINE=TREESTORE;

CREATE TABLE `region` (
	`R_REGIONKEY` INT(11) NOT NULL,
	`R_NAME` CHAR(25) NULL DEFAULT NULL COLLATE 'latin1_bin',
	`R_COMMENT` VARCHAR(152) NULL DEFAULT NULL COLLATE 'latin1_bin',
	PRIMARY KEY (`R_REGIONKEY`)
)
COLLATE='latin1_swedish_ci'
ENGINE=TREESTORE;
CREATE TABLE `supplier` (
	`S_SUPPKEY` INT(11) NOT NULL,
	`S_NATIONKEY` INT(11) NULL DEFAULT NULL,
	`S_COMMENT` VARCHAR(102) NULL DEFAULT NULL COLLATE 'latin1_bin',
	`S_NAME` CHAR(25) NULL DEFAULT NULL COLLATE 'latin1_bin',
	`S_ADDRESS` VARCHAR(40) NULL DEFAULT NULL COLLATE 'latin1_bin',
	`S_PHONE` CHAR(15) NULL DEFAULT NULL COLLATE 'latin1_bin',
	`S_ACCTBAL` DECIMAL(10,2) NULL DEFAULT NULL,
	PRIMARY KEY (`S_SUPPKEY`),
	INDEX `SUPPLIER_FK1` (`S_NATIONKEY`)
)
COLLATE='latin1_swedish_ci'
ENGINE=TREESTORE;